# Generated by Django 5.0.6 on 2024-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('D', 'Daily')], default='M', max_length=2)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
